---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuanhuan.
--- DateTime: 2020/10/26 11:22
---

---@class failureNode : DecoratorNode
failureNode = BaseClass(DecoratorNode)

function failureNode:Tick(delta_time)
    local state = self._children[1]:Tick(delta_time)
    if state == eNodeState.Success then
        return eNodeState.Failure
    end
    return state
end

