---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuanhuan.
--- DateTime: 2023/4/2 13:11
---

---@class ActionNode : TaskNode
ActionNode = BaseClass(TaskNode)

function ActionNode:IsAction()
    return true
end