---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuanhuan.
--- DateTime: 2023/4/1 16:52
---

---@class ConditionNode : TaskNode
ConditionNode = BaseClass(TaskNode)

function ConditionNode:IsCondition()
    return true
end