---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/4/1 16:52
---

---@class conditionNode : taskNode
conditionNode = simple_class(taskNode)

function conditionNode:isCondition()
    return true
end