---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuanhuan.
--- DateTime: 2020/11/23 19:12
---

---@class moveToPositionNode : ActionNode
moveToPositionNode = BaseClass(ActionNode)

local MapManager = CS.MapManagerInterface
local IsPositionEqual = MapManager.IsPositionEqual
local GetEntityPos = MapManager.GetTilemapObjectPosition
local MoveToPosition = MapManager.MoveToPosition
local StopMove = MapManager.StopMove

function moveToPositionNode:Start()
    self:SetSharedVar("playState", playStateEnum.eStart)
    local targetPos = self:GetSharedVar("targetPos")
    local entityPos = GetEntityPos(self.owner.guid)
    if targetPos == nil or IsPositionEqual(entityPos, targetPos) then
        self:SetSharedVar("playState", playStateEnum.eEnd)
        return eNodeState.Failure
    else
        self:SetSharedVar("animState", animatorStateEnum.eWalk)
        MoveToPosition(self.owner.guid, targetPos, function()
            self:moveFinish()
        end)
        return eNodeState.Running
    end
end

function moveToPositionNode:Abort()
    StopMove(self.owner.guid)
    self:moveFinish()
end

function moveToPositionNode:moveFinish()
    self:SetSharedVar("animState", animatorStateEnum.eIdle)
    self:SetSharedVar("playState", playStateEnum.eEnd)
    self:SetState(eNodeState.Success)
end