---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuanhuan.
--- DateTime: 2020/12/07 16:59
---

---@class randomPositionNode : ActionNode
randomPositionNode = BaseClass(ActionNode)

local MapManager = CS.MapManagerInterface
local IsCanMove = MapManager.IsCanMove

function randomPositionNode:Start()
    local pos = self:getNextPos()
    if IsCanMove(pos) then
        self:SetSharedVar("targetPos", pos)
        return eNodeState.Success
    else
        return eNodeState.Failure
    end
end