---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/4/1 17:30
---

---@class isActiveNode : conditionNode
isActiveNode = simple_class(conditionNode)

function isActiveNode:update()
    local entity = self:getSharedVar(self.owner.guid)
    return entity.gameObject.isActiveSelf and eNodeState.success or eNodeState.failure
end